window.MIST_SHEET_MANIFEST = {
  "image": "C:\\Users\\polar\\Downloads\\HP-ZBCkagAAHoCr.jfif",
  "size": {
    "width": 1920,
    "height": 1280
  },
  "grid": {
    "rows": 5,
    "cols": 16,
    "x0": 24,
    "y0": 150,
    "step_x": 118,
    "step_y": 206,
    "cell_w": 108,
    "cell_h": 210
  },
  "cellCount": 80,
  "recognizedCount": 0,
  "priceCount": 80,
  "cells": [
    {
      "index": 1,
      "row": 1,
      "col": 1,
      "x": 24,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c01.png",
      "card_path": "cards\\r01_c01_card.png",
      "price_path": "prices\\r01_c01_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11161",
      "price_value": 11161,
      "status": "pending"
    },
    {
      "index": 2,
      "row": 1,
      "col": 2,
      "x": 142,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c02.png",
      "card_path": "cards\\r01_c02_card.png",
      "price_path": "prices\\r01_c02_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1111",
      "price_value": 1111,
      "status": "pending"
    },
    {
      "index": 3,
      "row": 1,
      "col": 3,
      "x": 260,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c03.png",
      "card_path": "cards\\r01_c03_card.png",
      "price_path": "prices\\r01_c03_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "77",
      "price_value": 77,
      "status": "pending"
    },
    {
      "index": 4,
      "row": 1,
      "col": 4,
      "x": 378,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c04.png",
      "card_path": "cards\\r01_c04_card.png",
      "price_path": "prices\\r01_c04_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1119",
      "price_value": 1119,
      "status": "pending"
    },
    {
      "index": 5,
      "row": 1,
      "col": 5,
      "x": 496,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c05.png",
      "card_path": "cards\\r01_c05_card.png",
      "price_path": "prices\\r01_c05_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "41",
      "price_value": 41,
      "status": "pending"
    },
    {
      "index": 6,
      "row": 1,
      "col": 6,
      "x": 614,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c06.png",
      "card_path": "cards\\r01_c06_card.png",
      "price_path": "prices\\r01_c06_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "61",
      "price_value": 61,
      "status": "pending"
    },
    {
      "index": 7,
      "row": 1,
      "col": 7,
      "x": 732,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c07.png",
      "card_path": "cards\\r01_c07_card.png",
      "price_path": "prices\\r01_c07_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11641",
      "price_value": 11641,
      "status": "pending"
    },
    {
      "index": 8,
      "row": 1,
      "col": 8,
      "x": 850,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c08.png",
      "card_path": "cards\\r01_c08_card.png",
      "price_path": "prices\\r01_c08_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "111514",
      "price_value": 111514,
      "status": "pending"
    },
    {
      "index": 9,
      "row": 1,
      "col": 9,
      "x": 968,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c09.png",
      "card_path": "cards\\r01_c09_card.png",
      "price_path": "prices\\r01_c09_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11",
      "price_value": 11,
      "status": "pending"
    },
    {
      "index": 10,
      "row": 1,
      "col": 10,
      "x": 1086,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c10.png",
      "card_path": "cards\\r01_c10_card.png",
      "price_path": "prices\\r01_c10_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "146",
      "price_value": 146,
      "status": "pending"
    },
    {
      "index": 11,
      "row": 1,
      "col": 11,
      "x": 1204,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c11.png",
      "card_path": "cards\\r01_c11_card.png",
      "price_path": "prices\\r01_c11_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11154449",
      "price_value": 11154449,
      "status": "pending"
    },
    {
      "index": 12,
      "row": 1,
      "col": 12,
      "x": 1322,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c12.png",
      "card_path": "cards\\r01_c12_card.png",
      "price_path": "prices\\r01_c12_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1464",
      "price_value": 1464,
      "status": "pending"
    },
    {
      "index": 13,
      "row": 1,
      "col": 13,
      "x": 1440,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c13.png",
      "card_path": "cards\\r01_c13_card.png",
      "price_path": "prices\\r01_c13_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1161",
      "price_value": 1161,
      "status": "pending"
    },
    {
      "index": 14,
      "row": 1,
      "col": 14,
      "x": 1558,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c14.png",
      "card_path": "cards\\r01_c14_card.png",
      "price_path": "prices\\r01_c14_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "61",
      "price_value": 61,
      "status": "pending"
    },
    {
      "index": 15,
      "row": 1,
      "col": 15,
      "x": 1676,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c15.png",
      "card_path": "cards\\r01_c15_card.png",
      "price_path": "prices\\r01_c15_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "661",
      "price_value": 661,
      "status": "pending"
    },
    {
      "index": 16,
      "row": 1,
      "col": 16,
      "x": 1794,
      "y": 150,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r01_c16.png",
      "card_path": "cards\\r01_c16_card.png",
      "price_path": "prices\\r01_c16_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11",
      "price_value": 11,
      "status": "pending"
    },
    {
      "index": 17,
      "row": 2,
      "col": 1,
      "x": 24,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c01.png",
      "card_path": "cards\\r02_c01_card.png",
      "price_path": "prices\\r02_c01_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "166000",
      "price_value": 166000,
      "status": "pending"
    },
    {
      "index": 18,
      "row": 2,
      "col": 2,
      "x": 142,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c02.png",
      "card_path": "cards\\r02_c02_card.png",
      "price_path": "prices\\r02_c02_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1111141",
      "price_value": 1111141,
      "status": "pending"
    },
    {
      "index": 19,
      "row": 2,
      "col": 3,
      "x": 260,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c03.png",
      "card_path": "cards\\r02_c03_card.png",
      "price_path": "prices\\r02_c03_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "230000",
      "price_value": 230000,
      "status": "pending"
    },
    {
      "index": 20,
      "row": 2,
      "col": 4,
      "x": 378,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c04.png",
      "card_path": "cards\\r02_c04_card.png",
      "price_path": "prices\\r02_c04_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "111191",
      "price_value": 111191,
      "status": "pending"
    },
    {
      "index": 21,
      "row": 2,
      "col": 5,
      "x": 496,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c05.png",
      "card_path": "cards\\r02_c05_card.png",
      "price_path": "prices\\r02_c05_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1040000",
      "price_value": 1040000,
      "status": "pending"
    },
    {
      "index": 22,
      "row": 2,
      "col": 6,
      "x": 614,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c06.png",
      "card_path": "cards\\r02_c06_card.png",
      "price_path": "prices\\r02_c06_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "494000",
      "price_value": 494000,
      "status": "pending"
    },
    {
      "index": 23,
      "row": 2,
      "col": 7,
      "x": 732,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c07.png",
      "card_path": "cards\\r02_c07_card.png",
      "price_path": "prices\\r02_c07_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "109000",
      "price_value": 109000,
      "status": "pending"
    },
    {
      "index": 24,
      "row": 2,
      "col": 8,
      "x": 850,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c08.png",
      "card_path": "cards\\r02_c08_card.png",
      "price_path": "prices\\r02_c08_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "106000",
      "price_value": 106000,
      "status": "pending"
    },
    {
      "index": 25,
      "row": 2,
      "col": 9,
      "x": 968,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c09.png",
      "card_path": "cards\\r02_c09_card.png",
      "price_path": "prices\\r02_c09_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "59500",
      "price_value": 59500,
      "status": "pending"
    },
    {
      "index": 26,
      "row": 2,
      "col": 10,
      "x": 1086,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c10.png",
      "card_path": "cards\\r02_c10_card.png",
      "price_path": "prices\\r02_c10_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "109000",
      "price_value": 109000,
      "status": "pending"
    },
    {
      "index": 27,
      "row": 2,
      "col": 11,
      "x": 1204,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c11.png",
      "card_path": "cards\\r02_c11_card.png",
      "price_path": "prices\\r02_c11_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11411111",
      "price_value": 11411111,
      "status": "pending"
    },
    {
      "index": 28,
      "row": 2,
      "col": 12,
      "x": 1322,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c12.png",
      "card_path": "cards\\r02_c12_card.png",
      "price_path": "prices\\r02_c12_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "119111",
      "price_value": 119111,
      "status": "pending"
    },
    {
      "index": 29,
      "row": 2,
      "col": 13,
      "x": 1440,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c13.png",
      "card_path": "cards\\r02_c13_card.png",
      "price_path": "prices\\r02_c13_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "161644111",
      "price_value": 161644111,
      "status": "pending"
    },
    {
      "index": 30,
      "row": 2,
      "col": 14,
      "x": 1558,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c14.png",
      "card_path": "cards\\r02_c14_card.png",
      "price_path": "prices\\r02_c14_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "166111",
      "price_value": 166111,
      "status": "pending"
    },
    {
      "index": 31,
      "row": 2,
      "col": 15,
      "x": 1676,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c15.png",
      "card_path": "cards\\r02_c15_card.png",
      "price_path": "prices\\r02_c15_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11691111",
      "price_value": 11691111,
      "status": "pending"
    },
    {
      "index": 32,
      "row": 2,
      "col": 16,
      "x": 1794,
      "y": 356,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r02_c16.png",
      "card_path": "cards\\r02_c16_card.png",
      "price_path": "prices\\r02_c16_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1141941",
      "price_value": 1141941,
      "status": "pending"
    },
    {
      "index": 33,
      "row": 3,
      "col": 1,
      "x": 24,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c01.png",
      "card_path": "cards\\r03_c01_card.png",
      "price_path": "prices\\r03_c01_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "43500",
      "price_value": 43500,
      "status": "pending"
    },
    {
      "index": 34,
      "row": 3,
      "col": 2,
      "x": 142,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c02.png",
      "card_path": "cards\\r03_c02_card.png",
      "price_path": "prices\\r03_c02_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "19000",
      "price_value": 19000,
      "status": "pending"
    },
    {
      "index": 35,
      "row": 3,
      "col": 3,
      "x": 260,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c03.png",
      "card_path": "cards\\r03_c03_card.png",
      "price_path": "prices\\r03_c03_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "461611",
      "price_value": 461611,
      "status": "pending"
    },
    {
      "index": 36,
      "row": 3,
      "col": 4,
      "x": 378,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c04.png",
      "card_path": "cards\\r03_c04_card.png",
      "price_path": "prices\\r03_c04_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "38000",
      "price_value": 38000,
      "status": "pending"
    },
    {
      "index": 37,
      "row": 3,
      "col": 5,
      "x": 496,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c05.png",
      "card_path": "cards\\r03_c05_card.png",
      "price_path": "prices\\r03_c05_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "28000",
      "price_value": 28000,
      "status": "pending"
    },
    {
      "index": 38,
      "row": 3,
      "col": 6,
      "x": 614,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c06.png",
      "card_path": "cards\\r03_c06_card.png",
      "price_path": "prices\\r03_c06_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "20000",
      "price_value": 20000,
      "status": "pending"
    },
    {
      "index": 39,
      "row": 3,
      "col": 7,
      "x": 732,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c07.png",
      "card_path": "cards\\r03_c07_card.png",
      "price_path": "prices\\r03_c07_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "111116",
      "price_value": 111116,
      "status": "pending"
    },
    {
      "index": 40,
      "row": 3,
      "col": 8,
      "x": 850,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c08.png",
      "card_path": "cards\\r03_c08_card.png",
      "price_path": "prices\\r03_c08_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "13000",
      "price_value": 13000,
      "status": "pending"
    },
    {
      "index": 41,
      "row": 3,
      "col": 9,
      "x": 968,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c09.png",
      "card_path": "cards\\r03_c09_card.png",
      "price_path": "prices\\r03_c09_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "16116911",
      "price_value": 16116911,
      "status": "pending"
    },
    {
      "index": 42,
      "row": 3,
      "col": 10,
      "x": 1086,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c10.png",
      "card_path": "cards\\r03_c10_card.png",
      "price_path": "prices\\r03_c10_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11466168",
      "price_value": 11466168,
      "status": "pending"
    },
    {
      "index": 43,
      "row": 3,
      "col": 11,
      "x": 1204,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c11.png",
      "card_path": "cards\\r03_c11_card.png",
      "price_path": "prices\\r03_c11_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "13000",
      "price_value": 13000,
      "status": "pending"
    },
    {
      "index": 44,
      "row": 3,
      "col": 12,
      "x": 1322,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c12.png",
      "card_path": "cards\\r03_c12_card.png",
      "price_path": "prices\\r03_c12_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "111111",
      "price_value": 111111,
      "status": "pending"
    },
    {
      "index": 45,
      "row": 3,
      "col": 13,
      "x": 1440,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c13.png",
      "card_path": "cards\\r03_c13_card.png",
      "price_path": "prices\\r03_c13_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1169411",
      "price_value": 1169411,
      "status": "pending"
    },
    {
      "index": 46,
      "row": 3,
      "col": 14,
      "x": 1558,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c14.png",
      "card_path": "cards\\r03_c14_card.png",
      "price_path": "prices\\r03_c14_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11691411",
      "price_value": 11691411,
      "status": "pending"
    },
    {
      "index": 47,
      "row": 3,
      "col": 15,
      "x": 1676,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c15.png",
      "card_path": "cards\\r03_c15_card.png",
      "price_path": "prices\\r03_c15_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "119411",
      "price_value": 119411,
      "status": "pending"
    },
    {
      "index": 48,
      "row": 3,
      "col": 16,
      "x": 1794,
      "y": 562,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r03_c16.png",
      "card_path": "cards\\r03_c16_card.png",
      "price_path": "prices\\r03_c16_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11161911",
      "price_value": 11161911,
      "status": "pending"
    },
    {
      "index": 49,
      "row": 4,
      "col": 1,
      "x": 24,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c01.png",
      "card_path": "cards\\r04_c01_card.png",
      "price_path": "prices\\r04_c01_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "16111",
      "price_value": 16111,
      "status": "pending"
    },
    {
      "index": 50,
      "row": 4,
      "col": 2,
      "x": 142,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c02.png",
      "card_path": "cards\\r04_c02_card.png",
      "price_path": "prices\\r04_c02_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "9500",
      "price_value": 9500,
      "status": "pending"
    },
    {
      "index": 51,
      "row": 4,
      "col": 3,
      "x": 260,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c03.png",
      "card_path": "cards\\r04_c03_card.png",
      "price_path": "prices\\r04_c03_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "7000",
      "price_value": 7000,
      "status": "pending"
    },
    {
      "index": 52,
      "row": 4,
      "col": 4,
      "x": 378,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c04.png",
      "card_path": "cards\\r04_c04_card.png",
      "price_path": "prices\\r04_c04_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "48200",
      "price_value": 48200,
      "status": "pending"
    },
    {
      "index": 53,
      "row": 4,
      "col": 5,
      "x": 496,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c05.png",
      "card_path": "cards\\r04_c05_card.png",
      "price_path": "prices\\r04_c05_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "2130000",
      "price_value": 2130000,
      "status": "pending"
    },
    {
      "index": 54,
      "row": 4,
      "col": 6,
      "x": 614,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c06.png",
      "card_path": "cards\\r04_c06_card.png",
      "price_path": "prices\\r04_c06_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "4000",
      "price_value": 4000,
      "status": "pending"
    },
    {
      "index": 55,
      "row": 4,
      "col": 7,
      "x": 732,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c07.png",
      "card_path": "cards\\r04_c07_card.png",
      "price_path": "prices\\r04_c07_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "355000",
      "price_value": 355000,
      "status": "pending"
    },
    {
      "index": 56,
      "row": 4,
      "col": 8,
      "x": 850,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c08.png",
      "card_path": "cards\\r04_c08_card.png",
      "price_path": "prices\\r04_c08_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "6141181",
      "price_value": 6141181,
      "status": "pending"
    },
    {
      "index": 57,
      "row": 4,
      "col": 9,
      "x": 968,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c09.png",
      "card_path": "cards\\r04_c09_card.png",
      "price_path": "prices\\r04_c09_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "183500",
      "price_value": 183500,
      "status": "pending"
    },
    {
      "index": 58,
      "row": 4,
      "col": 10,
      "x": 1086,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c10.png",
      "card_path": "cards\\r04_c10_card.png",
      "price_path": "prices\\r04_c10_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "145500",
      "price_value": 145500,
      "status": "pending"
    },
    {
      "index": 59,
      "row": 4,
      "col": 11,
      "x": 1204,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c11.png",
      "card_path": "cards\\r04_c11_card.png",
      "price_path": "prices\\r04_c11_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "34000",
      "price_value": 34000,
      "status": "pending"
    },
    {
      "index": 60,
      "row": 4,
      "col": 12,
      "x": 1322,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c12.png",
      "card_path": "cards\\r04_c12_card.png",
      "price_path": "prices\\r04_c12_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "29500",
      "price_value": 29500,
      "status": "pending"
    },
    {
      "index": 61,
      "row": 4,
      "col": 13,
      "x": 1440,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c13.png",
      "card_path": "cards\\r04_c13_card.png",
      "price_path": "prices\\r04_c13_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "174500",
      "price_value": 174500,
      "status": "pending"
    },
    {
      "index": 62,
      "row": 4,
      "col": 14,
      "x": 1558,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c14.png",
      "card_path": "cards\\r04_c14_card.png",
      "price_path": "prices\\r04_c14_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "151500",
      "price_value": 151500,
      "status": "pending"
    },
    {
      "index": 63,
      "row": 4,
      "col": 15,
      "x": 1676,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c15.png",
      "card_path": "cards\\r04_c15_card.png",
      "price_path": "prices\\r04_c15_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "146500",
      "price_value": 146500,
      "status": "pending"
    },
    {
      "index": 64,
      "row": 4,
      "col": 16,
      "x": 1794,
      "y": 768,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r04_c16.png",
      "card_path": "cards\\r04_c16_card.png",
      "price_path": "prices\\r04_c16_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "141141",
      "price_value": 141141,
      "status": "pending"
    },
    {
      "index": 65,
      "row": 5,
      "col": 1,
      "x": 24,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c01.png",
      "card_path": "cards\\r05_c01_card.png",
      "price_path": "prices\\r05_c01_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1151111",
      "price_value": 1151111,
      "status": "pending"
    },
    {
      "index": 66,
      "row": 5,
      "col": 2,
      "x": 142,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c02.png",
      "card_path": "cards\\r05_c02_card.png",
      "price_path": "prices\\r05_c02_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "534000",
      "price_value": 534000,
      "status": "pending"
    },
    {
      "index": 67,
      "row": 5,
      "col": 3,
      "x": 260,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c03.png",
      "card_path": "cards\\r05_c03_card.png",
      "price_path": "prices\\r05_c03_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "504000",
      "price_value": 504000,
      "status": "pending"
    },
    {
      "index": 68,
      "row": 5,
      "col": 4,
      "x": 378,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c04.png",
      "card_path": "cards\\r05_c04_card.png",
      "price_path": "prices\\r05_c04_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "111441999",
      "price_value": 111441999,
      "status": "pending"
    },
    {
      "index": 69,
      "row": 5,
      "col": 5,
      "x": 496,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c05.png",
      "card_path": "cards\\r05_c05_card.png",
      "price_path": "prices\\r05_c05_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1119949",
      "price_value": 1119949,
      "status": "pending"
    },
    {
      "index": 70,
      "row": 5,
      "col": 6,
      "x": 614,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c06.png",
      "card_path": "cards\\r05_c06_card.png",
      "price_path": "prices\\r05_c06_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "895000",
      "price_value": 895000,
      "status": "pending"
    },
    {
      "index": 71,
      "row": 5,
      "col": 7,
      "x": 732,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c07.png",
      "card_path": "cards\\r05_c07_card.png",
      "price_path": "prices\\r05_c07_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11111111",
      "price_value": 11111111,
      "status": "pending"
    },
    {
      "index": 72,
      "row": 5,
      "col": 8,
      "x": 850,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c08.png",
      "card_path": "cards\\r05_c08_card.png",
      "price_path": "prices\\r05_c08_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "14449194",
      "price_value": 14449194,
      "status": "pending"
    },
    {
      "index": 73,
      "row": 5,
      "col": 9,
      "x": 968,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c09.png",
      "card_path": "cards\\r05_c09_card.png",
      "price_path": "prices\\r05_c09_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "52000",
      "price_value": 52000,
      "status": "pending"
    },
    {
      "index": 74,
      "row": 5,
      "col": 10,
      "x": 1086,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c10.png",
      "card_path": "cards\\r05_c10_card.png",
      "price_path": "prices\\r05_c10_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11199191",
      "price_value": 11199191,
      "status": "pending"
    },
    {
      "index": 75,
      "row": 5,
      "col": 11,
      "x": 1204,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c11.png",
      "card_path": "cards\\r05_c11_card.png",
      "price_path": "prices\\r05_c11_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1144491494",
      "price_value": 1144491494,
      "status": "pending"
    },
    {
      "index": 76,
      "row": 5,
      "col": 12,
      "x": 1322,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c12.png",
      "card_path": "cards\\r05_c12_card.png",
      "price_path": "prices\\r05_c12_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "114491169",
      "price_value": 114491169,
      "status": "pending"
    },
    {
      "index": 77,
      "row": 5,
      "col": 13,
      "x": 1440,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c13.png",
      "card_path": "cards\\r05_c13_card.png",
      "price_path": "prices\\r05_c13_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "1144199114941",
      "price_value": 1144199114941,
      "status": "pending"
    },
    {
      "index": 78,
      "row": 5,
      "col": 14,
      "x": 1558,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c14.png",
      "card_path": "cards\\r05_c14_card.png",
      "price_path": "prices\\r05_c14_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "166491941",
      "price_value": 166491941,
      "status": "pending"
    },
    {
      "index": 79,
      "row": 5,
      "col": 15,
      "x": 1676,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c15.png",
      "card_path": "cards\\r05_c15_card.png",
      "price_path": "prices\\r05_c15_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "119919441",
      "price_value": 119919441,
      "status": "pending"
    },
    {
      "index": 80,
      "row": 5,
      "col": 16,
      "x": 1794,
      "y": 974,
      "w": 108,
      "h": 210,
      "cell_path": "cells\\r05_c16.png",
      "card_path": "cards\\r05_c16_card.png",
      "price_path": "prices\\r05_c16_price.png",
      "card_name": "",
      "card_number": "",
      "set_label": "",
      "price_text": "11444919",
      "price_value": 11444919,
      "status": "pending"
    }
  ]
};
